#!/bin/bash
# -----------------------------------------------------------------------------
# Liblarch - a library to handle directed acyclic graphs
# Copyright (c) 2011-2012 - Lionel Dricot & Izidor Matušov
#
# This code is based on a part of Getting Things GNOME! code published
# under GNU GPLv3 - https://launchpad.net/gtg
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------

# PPA where to push changes
PPA="gtg-daily"
# For which distribution we want to build it
DISTRIBUTION="oneiric"
# Who is the maintainer? Whose GPG key should be used to sign the package?
MAINTAINER="Izidor Matušov <izidor.matusov@gmail.com>"

if ! which py2dsc > /dev/null
then
    echo "py2dsc is missing" >&2
    echo >&2
    echo "Install missing package:" >&2
    echo "sudo apt-get install python-stdeb" >&2
    exit 1
fi

if [ ! $# -eq 1 -o \( "$1" != "local" -a "$1" != "remote" \) ]; then
    echo "usage: $0 <local|remote>"
    exit 1
else
    usage="$1"
fi

build_package() {
    name="$1"

    echo "Building package $name"

    rm -rf build
    mkdir build

    tarfile=$(basename dist/$name-*)
    dirname=${tarfile%.tar.gz}
    
    mv dist/$tarfile build

    pushd build

    # Build just one package
    tar xf $tarfile
    rm $tarfile
    sed -i -e 's:standalone_packages = \[.*\]:standalone_packages = ["'$name'"]:' $dirname/setup.py
    tar cfz $tarfile $dirname
    rm -r $dirname

    py2dsc --suite "$DISTRIBUTION" --maintainer "$MAINTAINER" $tarfile
    # From this moment we use '-' instead of '_'
    dirname=${dirname/_/-}

    cd deb_dist/$dirname
    debuild -S -sa -us -us || exit $?

    if [ "$usage" == "local" ]; then
        dpkg-buildpackage -rfakeroot
        cd ..
        mv -v *.deb ../../dist/
    else
        cd ..
        dput $PPA *.changes
    fi

    popd
    rm -rf build
}

rm -rf dist/
echo "Creating source distribution"
python setup.py sdist > /dev/null

build_package "liblarch"
build_package "liblarch_gtk"

# cleaning
rm -rf build
